imports:
    - {resource: form_fieldtype_handlers.yml}
    - {resource: fieldtype_form_types.yml}
    - {resource: form_types.yml}

parameters:
    netgen.ezforms.form.fieldtype_handler_registry.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandlerRegistry
    netgen.ezforms.form.extension.fieldtype.class: Netgen\Bundle\EzFormsBundle\Form\Extension\FieldTypeTypeExtension

services:
    # Services tagged with 'netgen.ezforms.form.fieldtype_handler' will be registered
    # to this one during service container compilation. See imported resources.
    netgen.ezforms.form.fieldtype_handler_registry:
        class: %netgen.ezforms.form.fieldtype_handler_registry.class%

    netgen.ezforms.form.extension.fieldtype:
        class: %netgen.ezforms.form.extension.fieldtype.class%
        tags:
            - {name: form.type_extension, alias: form}
